[project]
authors = ["rd4com <144297616+rd4com@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "MojoTerminalUi"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"
license = "MIT"
license-file = "LICENSE"

[tasks]
build_pkg = { cmd = ["mojo", "package", ".", "-o", "build/ui-terminal-mojo.mojopkg"] }

[dependencies]
modular = ">=25.5.0.dev2025070207,<=25.5.0.dev2025070207"
